name: Deploy Mulberry-AI to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine output directory
        id: set_output_dir
        run: |
          if [ -d "public" ]; then
            echo "output_dir=public" >> "$GITHUB_OUTPUT"
          else
            echo "output_dir=." >> "$GITHUB_OUTPUT"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: none
          build_root: ${{ steps.set_output_dir.outputs.output_dir }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.set_output_dir.outputs.output_dir }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
